### ISSUE TITLE
package.json malformed config

### ISSUE THREAD

**Issue by SeanAlexanderHarris** [thenativeweb/wolkenkit-nevercompletedgame#3]
On running "wolkenkit start", getting variations on:

package.json contains malformed configuration (wolkenkit.environments['default'].api should NOT have additional properties)

**Comment by goloroden** [comment]
Sorry for the inconveniences 😢 

The problem here is that the `master` branch already contains changes that only work with the `latest` version of wolkenkit, not with the current stable one (which right now is 3.1.0).

To make things work, please use this commit: https://github.com/thenativeweb/wolkenkit-nevercompletedgame/commit/58d8b629c004d10d7fa5643552dfb4cf2e1d3131

**Comment by SeanAlexanderHarris** [comment]
Alternatively, could I update to the latest version of wolkenkit?

**Comment by goloroden** [comment]
Theoretically yes, but latest is highly moving and not guaranteed to work. The *way* more reliable approach is to go back a few commits here.

**Comment by SeanAlexanderHarris** [comment]
Roger wilco :) Many thanks 👍

**Comment by goloroden** [comment]
Roger Wilco? From Space Quest?

**Comment by SeanAlexanderHarris** [comment]
My man. 🥇
